config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  get '/post',      to: 'posts#new'
  post '/post',     to: 'posts#create'
  get '/login',     to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  before_create :create_remember_token

  has_secure_password
  has_many :posts

  def self.new_token
    SecureRandom.urlsafe_base64
  end
  
  def self.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end
  
  def create_remember_token
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in to post!"
      redirect_to root_url
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(user_params)
    @post.user_id = @current_user.id
    if @post.save
      redirect_to root_url
    else
      render 'new'
    end
  end

  def index
    @posts = Post.all
  end

  private
    def user_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      log_in(@user)
      flash[:success] = "Hi member! You were successfully logged in!"
      redirect_to root_url
    else
      flash.now[:warning] = "There was no email/password match!"
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    flash[:success] = "You were logged out of the Member's Club!"
    redirect_to root_url
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def full_title(page_title = '')
    base_title = "Member's Club"
    if page_title.empty?
      base_title
    else
      base_title + " | " + page_title
    end
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def logged_in?
    !current_user.nil?
  end

  def log_in(user)
    user.create_remember_token
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def current_user
    if(token = cookies[:remember_token])
      @current_user ||= User.find_by(remember_digest: User.digest(token))
    else
      nil
    end
  end

  def current_user=(user)
    @current_user = user
  end

  def log_out
    @current_user.forget
    @current_user = nil
    cookies.delete(:remember_token)
  end

end

app/views/layouts/_header.html.erb
<%= link_to "Home", root_path %>
<% if logged_in? %>  
  <%= link_to "Log out!", logout_path, method: :delete %>
  <%= link_to "Write a post", post_path %>
<% else %>
  <%= link_to "Log in", login_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <title><%= full_title(yield(:title)) %></title>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <h1><%= yield(:title) %></h1>
    <% flash.each do |key, value| %>
      <%= content_tag :div, value, class: "flash #{key}" %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/_post.html.erb
<li>
  <h3><%= post.title %></h3>
  <p><%= post.body %></p>
  
  <% if logged_in? %>
    <i><%= post.user.name %></i>
  <% end %>
</li>

app/views/posts/index.html.erb
<h1>Posts</h1>
<ul>
  <%= render @posts %>
</ul>

app/views/posts/new.html.erb
<% provide(:title, "New Post") %>

<% if @post.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@post.errors.count, "error") %>.
    </div>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @post, url: post_path do |f| %>
  <%= f.label :title, "Title:" %>
  <%= f.text_field :title %>
  
  <%= f.label :body, "Content:" %>
  <%= f.text_area :body %>

  <%= f.submit "Submit post!" %>
<% end %>